services:
  backend:
    build: ./backend
    container_name: yt-backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - publicVideo:/usr/public
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - ytengine
    command: npm run dev

  redis:
    image: redis:7
    container_name: yt-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - ytengine

  worker-transcode:
    build: ./workers/worker-transcode
    restart: always
    env_file: ./backend/.env
    volumes:
      - publicVideo:/usr/public
    depends_on:
      - redis
    networks:
      - ytengine
    command: node src/init.js
    deploy:
      replicas: 5
      resources:
        limits: 
          cpus: '0.5'
        reservations:
          cpus: '0.25'

  worker-hls:
    build: ./workers/worker-hls
    restart: always
    env_file: ./backend/.env
    volumes:
      - publicVideo:/usr/public
    depends_on:
      - redis
    networks:
      - ytengine
    command: node src/init.js
    deploy:
      replicas: 5
      resources:
        limits: 
          cpus: '0.5'
        reservations:
          cpus: '0.25'

  ws:
    build: ./backend
    container_name: yt-ws
    restart: always
    env_file: ./backend/.env
    ports:
      - "4000:8080"
    depends_on:
      - redis
    networks:
      - ytengine
    command: node src/sockets/ws.js

volumes:
  publicVideo:

networks:
  ytengine: